// ignore_for_file: constant_identifier_names

const TILE_SIZE = 16.0;
const CAMERA_ZOOM = 2.0;
const JOYSTICK_ENABLED = false;
const CRAFT_MENU_WIDTH = 600.0;
const CRAFT_MENU_HEIGHT = 400.0;
const GAME_MENU_WIDTH = 400.0;
const TOOL_MENU_WIDTH = 400.0;
const SEED_MENU_WIDTH = 400.0;
const INVENTORY_ITEM_BAR_COUNT = 8;
const INVENTORY_MENU_WIDTH = 600.0;
// const INVENTORY_MENU_HEIGHT = 400.0;
const INVENTORY_MOVE_WHEN_SHIFT_PRESSED = 5;
